### PR TITLE
Create AR-VR.md

### PR DESCRIPTION
**Pull request by Ishaan28malik**
Added new Resources related to Augmented and Virtual Reality.

### CODE REVIEW

**Comment by Ishaan28malik** [comment]
@saranshkataria review required.

**Comment by Ishaan28malik** [comment]
@gaurav-gogia please review.

**Comment by gaurav-gogia** [comment]
Hey, it looks good to me. Thanks for sharing resources :)

**Review by gaurav-gogia — APPROVED** [review]

**Comment by saranshkataria** [comment]
LGTM, Thanks!

**Pull request merged**
