### PR TITLE
Starting with iOS Readme. 

### PR DESCRIPTION
**Pull request by Aviral190694**
Will send incremental PR's for iOS starter guide as I research.

### CODE REVIEW

**Comment by Aviral190694** [comment]
@saranshkataria tagging you so we can merge this. In this week I will populate the list so people can find meaningful information.

**Comment by saranshkataria** [comment]
@Aviral190694 Thanks for this! Could you please add a link to it in the main README.MD file as well? Also, we are trying to keep these to a list of resources, not a blog post style format, so can we not have the general advice sections in there?

**Comment by Aviral190694** [comment]
@saranshkataria ya can surely remove stuff. Will update in sometime also will link it to the main README.MD

**Comment by Aviral190694** [comment]
@saranshkataria check and let me know if you want any more fixes.

**Comment by saranshkataria** [comment]
Made some changes, Thanks for the links!

**Pull request merged**
