### PR TITLE
R language Related Resources Added

### PR DESCRIPTION
**Pull request by itaniyagupta**

### CODE REVIEW

**Comment by harshitjuneja** [comment]
I see this is a single course on data-camp. We should have a single link to the course, rather than links to individual lessons.

**Comment by itaniyagupta** [comment]
> I see this is a single course on data-camp. We should have a single link to the course, rather than links to individual lessons.

Hi, these all are different courses (not lessons) . These courses are under a same track (R Programmer). So, i did up in different links. 

If you think then also, it need changes, do revert back.

**Comment by harshitjuneja** [comment]
Looks good in that case. Thanks for the PR. Merging 💯

**Comment by itaniyagupta** [comment]
> Looks good in that case. Thanks for the PR. Merging 💯

Thanks for merging .😊
I Like to contribute as much as i can.

**Pull request merged**
