### PR TITLE
Update Machine_Learning.md

### PR DESCRIPTION
**Pull request by Ishaan28malik**
Updated new resources in Community-Curated-Resources

### CODE REVIEW

**Comment by Ishaan28malik** [comment]
@saranshkataria need a Review.

**Comment by Ishaan28malik** [comment]
@gaurav-gogia please review.

**Comment by gaurav-gogia** [comment]
Looks good :)

**Review by gaurav-gogia — APPROVED** [review]

**Comment by saranshkataria** [comment]
LGTM, Thanks!

**Pull request merged**
