### PR TITLE
added go resources

### PR DESCRIPTION
**Pull request by gaurav-gogia**

### CODE REVIEW

**Comment by saranshkataria** [comment]
@DesmondANIMUS how does one get access to the private courses?

**Comment by gaurav-gogia** [comment]
The link opens Udemy's website and over there they can request access.

**Comment by saranshkataria** [comment]
@DesmondANIMUS any special requirements to get access? Or anyone who asks for it gets it?

**Comment by gaurav-gogia** [comment]
Anyone can ask for it. Though all may not get it. It's just a "request access" button.

**Comment by saranshkataria** [comment]
Merged, thanks

**Pull request merged**
