### PR TITLE
Added Angular and Django resources

### PR DESCRIPTION
**Pull request by anuj9196**
added Angular and Django resources

**Angular Resources**

- Youtube playlist of 45 videos for beginner

**Django Resources**

- Added Django for girls
- Added Django Testing Youtube video

### CODE REVIEW

**Comment by saranshkataria** [comment]
@anuj9196 Testing is still a topic that should come under one of the 3 headings defined. I don't think it should be placed under a separate heading. Might be better to put it in the intermediate one?

**Comment by anuj9196** [comment]
Okay, I thought of to put it in separate subtopic to catch the attention of many developers. I figured out that many beginners and intermediate developers do not use testing. And it should be encouraged to use testing in every application no matter how easy/complex the application is.

**Comment by saranshkataria** [comment]
Can you please put it in the format and not as a separate heading. Also no need to mention Django girls twice, remove the second link

**Comment by saranshkataria** [comment]
Thanks. Merged!

**Pull request merged**
