### PR TITLE
Add JS resources

### PR DESCRIPTION
**Pull request by sidvishnoi**

### CODE REVIEW

**Comment by saranshkataria** [comment]
@sidvishnoi let's stick to the template and not create more subheadings?

**Comment by sidvishnoi** [comment]
I am not in support of "Expert" as a heading, so I changed it. "In-depth" is more encouraging for everyone to read. I would recommend changing this in other files also. 
Also, it's not easy and always meaningful to divide them in these 3 categories.

Please feel free to edit the PR if you feel like.

**Comment by saranshkataria** [comment]
@harshitjuneja @shubhamoy thoughts on changing expert to "in-depth"?  Also, what about the blogs part?

**Comment by harshitjuneja** [comment]
Both expert and in-depth somehow convey what they are about. I totally agree that labelling a section as expert brings a certain psycological impact with it. I suggest we go with in-depth.

However @sidvishnoi's comment has made me re-think our approach. How about having only 2 sections, 1. breif ouline of the subject 2. in depth approach. This template actually categorizes content instead of the consumer.

**Comment by harshitjuneja** [comment]
Let's not keep blogs separate.

**Comment by vabhishek-me** [comment]
Rather than having a section called Blogs, rename it to "Reading Material" cuz then we can add pdf links, HN links, Forum links, SO links etc.

**Comment by saranshkataria** [comment]
PDF HN links would be specific and they can be classified. The more generic blogs are the question here. What do we do about them

**Comment by saranshkataria** [comment]
I personally think blogs should be left out too. Specific posts can be put in but general blog hyperlinks would make it too long a list which will not be that useful. Or maybe have a separate md file dedicated to blogs only?

**Comment by saranshkataria** [comment]
@sidvishnoi would you make the corresponding changes in the PR so that it can be merged? :)

**Comment by sidvishnoi** [comment]
> @sidvishnoi would you make the corresponding changes in the PR so that it can be merged? :)

What's the final decision?

**Comment by saranshkataria** [comment]
That we are sticking to the template and not adding generic blogs

**Comment by sidvishnoi** [comment]
Please feel free to edit the headings and I'll learn for the next ones :slightly_smiling_face:

**Comment by saranshkataria** [comment]
@sidvishnoi all 3 blogs that you have added contain getting started resources so I would recommend adding them to the beginner section. Also, can we have that in another PR since there already have been too many changes in this one for just 3 links

**Pull request closed without merging**
